version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: lostfound_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: LostAndFound
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3310:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - lostfound_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  backend:
    build: ./backend
    container_name: lostfound_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.docker
    volumes:
      - ./backend:/app
      - ./backend/static:/app/static
    depends_on:
      - db
    networks:
      - lostfound_network

  frontend:
    build: ./frontend
    container_name: lostfound_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - lostfound_network

volumes:
  db_data:

networks:
  lostfound_network:
    driver: bridge